#ifndef __GPIOS_H
#define __GPIOS_H

#define PA0_OUT Config_GPIO(GPIOA, GPIO_Pin_0, GPIO_MODE_OUTPUT)
#define PA0_IN Config_GPIO(GPIOA, GPIO_Pin_0, GPIO_MODE_INPUT)
#define PA0_H Set_GPIO_High(GPIOA, GPIO_Pin_0)
#define PA0_L Set_GPIO_Low(GPIOA, GPIO_Pin_0)

#define PA1_OUT Config_GPIO(GPIOA, GPIO_Pin_1, GPIO_MODE_OUTPUT)
#define PA1_IN Config_GPIO(GPIOA, GPIO_Pin_1, GPIO_MODE_INPUT)
#define PA1_H Set_GPIO_High(GPIOA, GPIO_Pin_1)
#define PA1_L Set_GPIO_Low(GPIOA, GPIO_Pin_1)

#define PA2_OUT Config_GPIO(GPIOA, GPIO_Pin_2, GPIO_MODE_OUTPUT)
#define PA2_IN Config_GPIO(GPIOA, GPIO_Pin_2, GPIO_MODE_INPUT)
#define PA2_H Set_GPIO_High(GPIOA, GPIO_Pin_2)
#define PA2_L Set_GPIO_Low(GPIOA, GPIO_Pin_2)

#define PA3_OUT Config_GPIO(GPIOA, GPIO_Pin_3, GPIO_MODE_OUTPUT)
#define PA3_IN Config_GPIO(GPIOA, GPIO_Pin_3, GPIO_MODE_INPUT)
#define PA3_H Set_GPIO_High(GPIOA, GPIO_Pin_3)
#define PA3_L Set_GPIO_Low(GPIOA, GPIO_Pin_3)

#define PA4_OUT Config_GPIO(GPIOA, GPIO_Pin_4, GPIO_MODE_OUTPUT)
#define PA4_IN Config_GPIO(GPIOA, GPIO_Pin_4, GPIO_MODE_INPUT)
#define PA4_H Set_GPIO_High(GPIOA, GPIO_Pin_4)
#define PA4_L Set_GPIO_Low(GPIOA, GPIO_Pin_4)

#define PA5_OUT Config_GPIO(GPIOA, GPIO_Pin_5, GPIO_MODE_OUTPUT)
#define PA5_IN Config_GPIO(GPIOA, GPIO_Pin_5, GPIO_MODE_INPUT)
#define PA5_H Set_GPIO_High(GPIOA, GPIO_Pin_5)
#define PA5_L Set_GPIO_Low(GPIOA, GPIO_Pin_5)

#define PA6_OUT Config_GPIO(GPIOA, GPIO_Pin_6, GPIO_MODE_OUTPUT)
#define PA6_IN Config_GPIO(GPIOA, GPIO_Pin_6, GPIO_MODE_INPUT)
#define PA6_H Set_GPIO_High(GPIOA, GPIO_Pin_6)
#define PA6_L Set_GPIO_Low(GPIOA, GPIO_Pin_6)

#define PA7_OUT Config_GPIO(GPIOA, GPIO_Pin_7, GPIO_MODE_OUTPUT)
#define PA7_IN Config_GPIO(GPIOA, GPIO_Pin_7, GPIO_MODE_INPUT)
#define PA7_H Set_GPIO_High(GPIOA, GPIO_Pin_7)
#define PA7_L Set_GPIO_Low(GPIOA, GPIO_Pin_7)

#define PA8_OUT Config_GPIO(GPIOA, GPIO_Pin_8, GPIO_MODE_OUTPUT)
#define PA8_IN Config_GPIO(GPIOA, GPIO_Pin_8, GPIO_MODE_INPUT)
#define PA8_H Set_GPIO_High(GPIOA, GPIO_Pin_8)
#define PA8_L Set_GPIO_Low(GPIOA, GPIO_Pin_8)

#define PA9_OUT Config_GPIO(GPIOA, GPIO_Pin_9, GPIO_MODE_OUTPUT)
#define PA9_IN Config_GPIO(GPIOA, GPIO_Pin_9, GPIO_MODE_INPUT)
#define PA9_H Set_GPIO_High(GPIOA, GPIO_Pin_9)
#define PA9_L Set_GPIO_Low(GPIOA, GPIO_Pin_9)

#define PA10_OUT Config_GPIO(GPIOA, GPIO_Pin_10, GPIO_MODE_OUTPUT)
#define PA10_IN Config_GPIO(GPIOA, GPIO_Pin_10, GPIO_MODE_INPUT)
#define PA10_H Set_GPIO_High(GPIOA, GPIO_Pin_10)
#define PA10_L Set_GPIO_Low(GPIOA, GPIO_Pin_10)

#define PA11_OUT Config_GPIO(GPIOA, GPIO_Pin_11, GPIO_MODE_OUTPUT)
#define PA11_IN Config_GPIO(GPIOA, GPIO_Pin_11, GPIO_MODE_INPUT)
#define PA11_H Set_GPIO_High(GPIOA, GPIO_Pin_11)
#define PA11_L Set_GPIO_Low(GPIOA, GPIO_Pin_11)

#define PA12_OUT Config_GPIO(GPIOA, GPIO_Pin_12, GPIO_MODE_OUTPUT)
#define PA12_IN Config_GPIO(GPIOA, GPIO_Pin_12, GPIO_MODE_INPUT)
#define PA12_H Set_GPIO_High(GPIOA, GPIO_Pin_12)
#define PA12_L Set_GPIO_Low(GPIOA, GPIO_Pin_12)

#define PB0_OUT Config_GPIO(GPIOB, GPIO_Pin_0, GPIO_MODE_OUTPUT)
#define PB0_IN Config_GPIO(GPIOB, GPIO_Pin_0, GPIO_MODE_INPUT)
#define PB0_H Set_GPIO_High(GPIOB, GPIO_Pin_0)
#define PB0_L Set_GPIO_Low(GPIOB, GPIO_Pin_0)

#define PB1_OUT Config_GPIO(GPIOB, GPIO_Pin_1, GPIO_MODE_OUTPUT)
#define PB1_IN Config(GPIOB, GPIO_Pin_1, GPIO_MODE_INPUT)
#define PB1_H Set_GPIO_High(GPIOB, GPIO_Pin_1)
#define PB1_L Set_GPIO_Low(GPIOB, GPIO_Pin_1)

#define PB5_OUT Config_GPIO(GPIOB, GPIO_Pin_5, GPIO_MODE_OUTPUT)
#define PB5_IN Config(GPIOB, GPIO_Pin_5, GPIO_MODE_INPUT)
#define PB5_H Set_GPIO_High(GPIOB, GPIO_Pin_5)
#define PB5_L Set_GPIO_Low(GPIOB, GPIO_Pin_5)

#define PB6_OUT Config_GPIO(GPIOB, GPIO_Pin_6, GPIO_MODE_OUTPUT)
#define PB6_IN Config(GPIOB, GPIO_Pin_6, GPIO_MODE_INPUT)
#define PB6_H Set_GPIO_High(GPIOB, GPIO_Pin_6)
#define PB6_L Set_GPIO_Low(GPIOB, GPIO_Pin_6)

#define PB7_OUT Config_GPIO(GPIOB, GPIO_Pin_7, GPIO_MODE_OUTPUT)
#define PB7_IN Config(GPIOB, GPIO_Pin_7, GPIO_MODE_INPUT)
#define PB7_H Set_GPIO_High(GPIOB, GPIO_Pin_7)
#define PB7_L Set_GPIO_Low(GPIOB, GPIO_Pin_7)

#define PB8_OUT Config_GPIO(GPIOB, GPIO_Pin_8, GPIO_MODE_OUTPUT)
#define PB8_IN Config(GPIOB, GPIO_Pin_8, GPIO_MODE_INPUT)
#define PB8_H Set_GPIO_High(GPIOB, GPIO_Pin_8)
#define PB8_L Set_GPIO_Low(GPIOB, GPIO_Pin_8)

#define PB9_OUT Config_GPIO(GPIOB, GPIO_Pin_9, GPIO_MODE_OUTPUT)
#define PB9_IN Config(GPIOB, GPIO_Pin_9, GPIO_MODE_INPUT)
#define PB9_H Set_GPIO_High(GPIOB, GPIO_Pin_9)
#define PB9_L Set_GPIO_Low(GPIOB, GPIO_Pin_9)

#define PB10_OUT Config_GPIO(GPIOB, GPIO_Pin_10, GPIO_MODE_OUTPUT)
#define PB10_IN Config(GPIOB, GPIO_Pin_10, GPIO_MODE_INPUT)
#define PB10_H Set_GPIO_High(GPIOB, GPIO_Pin_10)
#define PB10_L Set_GPIO_Low(GPIOB, GPIO_Pin_10)

#define PB11_OUT Config_GPIO(GPIOB, GPIO_Pin_11, GPIO_MODE_OUTPUT)
#define PB11_IN Config(GPIOB, GPIO_Pin_11, GPIO_MODE_INPUT)
#define PB11_H Set_GPIO_High(GPIOB, GPIO_Pin_11)
#define PB11_L Set_GPIO_Low(GPIOB, GPIO_Pin_11)

#define PB12_OUT Config_GPIO(GPIOB, GPIO_Pin_12, GPIO_MODE_OUTPUT)
#define PB12_IN Config(GPIOB, GPIO_Pin_12, GPIO_MODE_INPUT)
#define PB12_H Set_GPIO_High(GPIOB, GPIO_Pin_12)
#define PB12_L Set_GPIO_Low(GPIOB, GPIO_Pin_12)

#define PB13_OUT Config_GPIO(GPIOB, GPIO_Pin_13, GPIO_MODE_OUTPUT)
#define PB13_IN Config(GPIOB, GPIO_Pin_13, GPIO_MODE_INPUT)
#define PB13_H Set_GPIO_High(GPIOB, GPIO_Pin_13)
#define PB13_L Set_GPIO_Low(GPIOB, GPIO_Pin_13)

#define PB14_OUT Config_GPIO(GPIOB, GPIO_Pin_14, GPIO_MODE_OUTPUT)
#define PB14_IN Config(GPIOB, GPIO_Pin_14, GPIO_MODE_INPUT)
#define PB14_H Set_GPIO_High(GPIOB, GPIO_Pin_14)
#define PB14_L Set_GPIO_Low(GPIOB, GPIO_Pin_14)

#define PB15_OUT Config_GPIO(GPIOB, GPIO_Pin_15, GPIO_MODE_OUTPUT)
#define PB15_IN Config(GPIOB, GPIO_Pin_15, GPIO_MODE_INPUT)
#define PB15_H Set_GPIO_High(GPIOB, GPIO_Pin_15)
#define PB15_L Set_GPIO_Low(GPIOB, GPIO_Pin_15)

#define PC13_OUT Config_GPIO(GPIOC, GPIO_Pin_13, GPIO_MODE_OUTPUT)
#define PC13_IN Config(GPIOC, GPIO_Pin_13, GPIO_MODE_INPUT)
#define PC13_H Set_GPIO_High(GPIOC, GPIO_Pin_13)
#define PC13_L Set_GPIO_Low(GPIOC, GPIO_Pin_13)

#define PC14_OUT Config_GPIO(GPIOC, GPIO_Pin_14, GPIO_MODE_OUTPUT)
#define PC14_IN Config(GPIOC, GPIO_Pin_14, GPIO_MODE_INPUT)
#define PC14_H Set_GPIO_High(GPIOC, GPIO_Pin_14)
#define PC14_L Set_GPIO_Low(GPIOC, GPIO_Pin_14)

#define PC15_OUT Config_GPIO(GPIOC, GPIO_Pin_15, GPIO_MODE_OUTPUT)
#define PC15_IN Config(GPIOC, GPIO_Pin_15, GPIO_MODE_INPUT)
#define PC15_H Set_GPIO_High(GPIOC, GPIO_Pin_15)
#define PC15_L Set_GPIO_Low(GPIOC, GPIO_Pin_15)

#include "stm32f10x.h"

typedef enum {
    GPIO_MODE_INPUT,
    GPIO_MODE_OUTPUT
} GPIO_Mode_TypeDef;

void Config_GPIO(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, GPIO_Mode_TypeDef Mode);
void Set_GPIO_High(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin);
void Set_GPIO_Low(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin);

#endif
